"""Add CVE fields

Revision ID: 0dcfcefe0aee
Revises: c1317080bf2d
Create Date: 2025-11-09 20:04:21.078251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcfcefe0aee'
down_revision = 'c1317080bf2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cve_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cve_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_column('cve_description')
        batch_op.drop_column('cvss_score')
        batch_op.drop_column('cve_id')

    # ### end Alembic commands ###
